version: '3.8'

services:
  db:
    image: mysql:latest
    platform: linux/x86_64
    command: >
      mysqld
        --character-set-server=utf8
        --collation-server=utf8_unicode_ci
        --skip-character-set-client-handshake
        --default-authentication-plugin=mysql_native_password
    volumes:
      - ./schema/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
